### ISSUE TITLE
Receiving fragmented packets does not work

### ISSUE THREAD

**Issue by ihatecompvir** [ihatecompvir/GoCentral#2]
Rock Band 3 sends several large packets to the JSON protocol and because of their size, they are fragmented. There is currently no support for fragmented packets in the [nex-go](https://github.com/ihatecompvir/nex-go) library that GoCentral uses and they are just ignored upon being received. 

Implementing support for incoming fragmented packets should automatically allow the large packets to be parsed and handled like normal.

**Comment by leftyfl1p** [comment]
Can you give me an example of when the client sends a fragmented packet to the server? I'm having trouble reproducing this. I had one instance where [this](https://github.com/ihatecompvir/nex-go/blob/master/rmc.go#L46) got triggered (I'm assuming this is it), but I'm failing to get it to reproduce even with client/server restarts.

**Comment by ihatecompvir** [comment]
Correct; any time you see that error it is because the server is just dropping the fragmented packet and setting the payload to an empty one I believe.

One common way to trigger the fragmented packets is to play on a save with a lot of scores. The game will try to send a giant packet containing a ton of song IDs and it is always fragmented. If you don't have that, I think the score upload packet at the post-song screen is also big enough to be sent fragmented.

**Comment by leftyfl1p** [comment]
Thanks. I'd seen fragmented packets before but wasn't sure where. Spent like 40 mins on and off clicking through menus attempting to trigger it.

**Comment by ihatecompvir** [comment]
Closing as this was fixed by a recent commit to my Nex-go fork
