### ISSUE TITLE
Matchmaking always returns the first gathering from the database

### ISSUE THREAD

**Issue by ihatecompvir** [ihatecompvir/GoCentral#3]
In the Matchmaking protocol's CheckForGatherings method, the Mongo driver's FindOne method is used to get a gathering, which returns the first gathering that doesn't belong to the searching player. Because of the way that FindOne works, it will always return the first gathering in the DB according to the natural order. This means that no matter how many people search, the same gathering is returned for all of them.
https://github.com/ihatecompvir/GoCentral/blob/9e3dec496e05bde2a3ccc1dd69bf030b85bd6a1c/server.go#L762

It would be good to switch this to returning a completely random gathering, otherwise matchmaking doesn't really work with multiple players searching at once. Once the "first" gathering is full, matchmaking effectively stops working until that gathering is terminated or a slot opens up.

**Comment by InvoxiPlayGames** [comment]
I've attempted to fix this by using the MongoDB Aggregate function with a sample size of 1 in ee52680 - from basic testing with just 2 players it seems to still work as normal, although I still don't know if it *does* provide random results.

**Comment by ihatecompvir** [comment]
Bit late on closing this one out, but this has been fixed by ee52680e0c86a5fb7f9a7bfbd9341d163b8c55a6
